joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 125

gripper_controller:
  type: effort_controllers/GripperActionController
  gains:
    finger_joint: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  joint: finger_joint 
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0